site_name: Tiếng Anh dễ hiểu - Comprehensible English
site_description: Tự học Tiếng Anh thông qua việc tiêu thụ nội dung Tiếng Anh dễ hiểu (Comprehensible English) và đắm chìm mình vào nội dung Tiếng Anh làm bởi người bản xứ cho người bản xứ (Immersion)
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Lộ trình':
    - 'Học từ đầu': 'hoc-tu-dau.md'
    - 'Đầu vào dễ hiểu': 'input-guide.md'
    - 'Đắm chìm vào ngoại ngữ': 'guide.md'
  - 'FAQ':
    - 'Câu hỏi thường gặp': 'faq.md'
  - 'IELTS & TOEIC':
    - 'IELTS': 'ielts.md'
    - 'TOEIC': 'toeic.md'
  - 'Tổng hợp':
    - 'Tài nguyên': 'resources.md'
    - 'Cộng đồng học': 'cong-dong.md'
  - 'Nội dung tiêu thụ':
    - 'Sách - Tiểu thuyết': 'sach.md'
    - 'Phim ảnh': 'phim-anh.md'
    - 'Youtube': 'youtube.md'
    - 'Podcasts & Audiobooks': 'podcasts.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false