site_name: Tiếng Anh dễ hiểu - Comprehensible English
site_description: Tự học Tiếng Anh thông qua việc tiêu thụ nội dung Tiếng Anh dễ hiểu (Comprehensible English) và đắm chìm mình vào nội dung Tiếng Anh làm bởi người bản xứ cho người bản xứ (Immersion)
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Lộ trình':
    - '160 ngày Tiếng Anh': 'hoc-tu-dau.md'
    - 'Đầu vào dễ hiểu': 'input-guide.md'
    - 'Immersion': 'guide.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
    - 'Cộng đồng học': 'cong-dong.md'
  - 'Media':
    - 'Books': 'sach.md'
    - 'Movies': 'phim-anh.md'
    - 'Youtube': 'youtube.md'
    - 'Podcasts': 'podcasts.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false